name:    fluxbb
version: "0.0.0"

dependencies:
- aeson
- base
- classy-prelude-yesod
- classy-prelude
- data-default
- esqueleto
- fast-logger
- file-embed
- http-client
- http-client-tls
- monad-logger
- persistent
- persistent-template
- persistent-postgresql
- shakespeare
- template-haskell
- yaml
- yesod
- yesod-auth-hashdb
- yesod-auth
- yesod-core
- yesod-form
- yesod-static
- wai
- wai-extra
- wai-logger
- warp

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  fluxbb:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fluxbb
