name:    fluxbb
version: "0.0.0"

dependencies:
- base
- yesod-core
- classy-prelude-yesod
- classy-prelude
- esqueleto
- monad-logger
- persistent
- persistent-template
- persistent-postgresql
- template-haskell
- yesod-auth-hashdb
- yesod-auth
- yesod-form
- wai
- wai-extra
- wai-logger
- warp

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  fluxbb:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fluxbb
